language: cpp

matrix:
    include:
        - os: linux
          dist: bionic
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-8']
          env: CXX=g++-8

        - os: osx
          osx_image: xcode10.1
          env: CXX=g++-8

        - os: windows
script:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        brew update;
        brew install gcc@8;
      fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" -o "${TRAVIS_OS_NAME}" = "linux" ]; then
        mkdir build;
        cd build;
        cmake -DCMAKE_BUILD_TYPE="Release" ..;
        make -j8;
      fi

    - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then
        mkdir build;
        cd build;
        cmake -G "Visual Studio 15 2017 Win64" ..;
        cmake --build . --config Release;
      fi


